[package]
name = "pixelflut_pac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
console = "0.15.8"
image = "0.25.2"
indicatif = "0.17.8"
